### ISSUE TITLE
SGE, possible "lost" executors in highly parallel pipeline

### ISSUE THREAD

**Issue by gdevenyi** [ssadedin/bpipe#185]
Thanks to the high memory fixes, I can now run a pipeline with 8+ stages on 1000+ inputs without any memory issues (see https://github.com/CobraLab/minc-bpipe-library for pipeline)

However, I seem to be running into some kind of accounting issue with executors which I can't quite place.

I run a pipeline like this:

``` groovy
beast = segment {
    beastnormalize + beastmask + beastextract
}

preprocess = segment {
    clean_and_center + n4correct + linear_bestlinreg + cutneckapplyautocrop + beast + QC
}

run {
 "%.mnc" * [preprocess]
}
```

Some of the above stages use more than one "proc" during run, which is properly submitted to a SGE smp parallel environment.

Now running

``` sh
#240 slots available in the cluster
$ bpipe run -n240 /path/to/pipeline.bpipe /path/to/inputs/*.mnc
```

What I have found is, at the end of the "beast" segment, the pipeline will sit waiting for stages in the "beast" segment to complete before submitting more jobs. Even if there are unfinished prior stages for other inputs and other finished "beast" stage outputs, "QC" doesn't start.

The ends up with some small number of inputs running on the cluster with bpipe waiting for them to finish before submitting other jobs for both prior and subsequent stages.

This leads me to believe there's an accounting issue with executors/procs/jobs.

Can you suggest any tests for this?

**Comment by ssadedin** [comment]
I believe I've now encountered this issue myself on another SGE-derived environment. I did a bit of digging and noticed that the last visible line in the log for commands that are never seen as completed is:

```
bpipe.executor.ThrottledDelegatingCommandExecutor   [70]    INFO    |6:24:29 Waiting for command to complete ...
```

Looking through the code I can see that this means the code is waiting in the loop where it looks for the SGE exit file to be created, which is supposed to be made by the template:

```bash
trap 'echo 255 > $jobDir/$CMD_EXIT_FILENAME;' HUP INT TERM QUIT KILL STOP USR1 USR2         
(                                                                                           
bash -e ${CMD_FILENAME.absolutePath}                                                        
)                                                                                           
                                                                                            
result=\$?                                                                                  
echo -n \$result > $jobDir/$CMD_EXIT_FILENAME                                               
exit \$result                                                                               
```

So the file `$jobDir/$CMD_EXIT_FILENAME` is meant to be created one way or another: if killed via the trap statement, otherwise via the echo at the end of the script. What I observe is that this file is not created, even though the commands seemingly completed. It would be useful to know if you're observing that too. Just use `bpipe status` to see which commands Bpipe thinks are still outstanding and then look for the file `.bpipe/commandtmp/<command id>/cmd.exit`. 

My conclusion is that there are some cases where the -notify command passed to qsub either doesn't send the signals, sends unexpected signals, or somehow the script gets killed while executing the signal handler.

I don't have a solution for this right now, but I am thinking about implementing a fallback where every 30 seconds or so it might send an explicit command to probe if a job finished or not.

Would be great to have any thoughts @gdevenyi as to whether the above is consistent with what you see or not.

**Comment by ssadedin** [comment]
One more follow up here: to anybody who experiences this, it would be useful to know if the following fixes the problem for you. In the file `templates/executor/sge-command.template.sh`, replace the following lines

```
(
bash -e ${CMD_FILENAME.absolutePath}
)

result=\$?
```

with 

```
(
bash -e ${CMD_FILENAME.absolutePath}
) &

wait \$!
```

I believe this should help, but would be great to have confirmation.

**Comment by ssadedin** [comment]
Change aaa835a is relevant to this issue.

**Comment by gdevenyi** [comment]
Thanks for all the changes on this, I'll have to re-setup a comparable test-bed, since I've stopped/restarted these pipelines to get their outputs working, the logs will be way too hard to parse.
