### ISSUE TITLE
cannot remove directory error

### ISSUE THREAD

**Issue by hh1985** [ssadedin/bpipe#201]
Hi, 
I tried to run bpipe 0.9.9.2 using docker and got the following error:
```
root@906c543a8b83:~/projects/ctDNA/code# bpipe
/usr/bin/bpipe: line 666: .bpipe/jobs/: Is a directory
rm: cannot remove '/root/.bpipedb/jobs/': Is a directory
ERROR:  Bpipe process did not create expected log file .bpipe/logs/.log after 3 seconds.  Please check output.
```
I changed the line "rm $JOBDB_FILE" to "rm -rf $JOBDB_FILE" and the error disappeared:

```
 JOBDB_FILE=~/.bpipedb/jobs/$BPIPE_PID
    if [ -e $JOBDB_FILE ];
    then
      rm $JOBDB_FILE;
    fi
    ln -s `pwd`/.bpipe/jobs/$BPIPE_PID  $JOBDB_FILE
```
I think this looks like a bug in bpipe.

Thanks,

-hh1985

**Comment by yunhailuo** [comment]
I'm wondering if this has been fixed and/or there is a proper workaround. I'm getting the same error recently. To be specific, there are two errors here when `$BPIPE_PID` is empty or undefined: 1) you can't echo to a dir: https://github.com/ssadedin/bpipe/blob/master/bin/bpipe#L782 and 2) the dir (instead of file) gets into rm error: https://github.com/ssadedin/bpipe/blob/master/bin/bpipe#L796 .

One other thing I'm seeing is this doesn't happen every runs and I didn't look into how to repeat that; I just rerun and ignore but it did come up from time to time.

@hh1985 or @ssadedin for help?
